package lib

const (
	MOB_ACTION_SPEC int = 1 << iota
	MOB_ACTION_SENTINEL
	MOB_ACTION_SCAVENGER
	MOB_ACTION_ISNPC
	MOB_ACTION_AWARE
	MOB_ACTION_AGGRESSIVE
	MOB_ACTION_STAY_ZONE
	MOB_ACTION_WIMPY
	MOB_ACTION_AGGR_EVIL
	MOB_ACTION_AGGR_GOOD
	MOB_ACTION_AGGR_NEUTRAL
	MOB_ACTION_MEMORY
	MOB_ACTION_HELPER
	MOB_ACTION_NOCHARM
	MOB_ACTION_NOSUMMON
	MOB_ACTION_NOSLEEP
	MOB_ACTION_NOBASH
	MOB_ACTION_NOBLIND
)

var MobActionChars = map[rune]string{
	'a': "SPEC",
	'b': "SENTINEL",
	'c': "SCAVENGER",
	'd': "ISNPC",
	'e': "AWARE",
	'f': "AGGRESSIVE",
	'g': "STAY_ZONE",
	'h': "WIMPY",
	'i': "AGGR_EVIL",
	'j': "AGGR_GOOD",
	'k': "AGGR_NEUTRAL",
	'l': "MEMORY",
	'm': "HELPER",
	'n': "NOCHARM",
	'o': "NOSUMMON",
	'p': "NOSLEEP",
	'q': "NOBASH",
	'r': "NOBLIND",
}

var MobActionBits = map[int]string{
	MOB_ACTION_SPEC:         "SPEC",
	MOB_ACTION_SENTINEL:     "SENTINEL",
	MOB_ACTION_SCAVENGER:    "SCAVENGER",
	MOB_ACTION_ISNPC:        "ISNPC",
	MOB_ACTION_AWARE:        "AWARE",
	MOB_ACTION_AGGRESSIVE:   "AGGRESSIVE",
	MOB_ACTION_STAY_ZONE:    "STAY_ZONE",
	MOB_ACTION_WIMPY:        "WIMPY",
	MOB_ACTION_AGGR_EVIL:    "AGGR_EVIL",
	MOB_ACTION_AGGR_GOOD:    "AGGR_GOOD",
	MOB_ACTION_AGGR_NEUTRAL: "AGGR_NEUTRAL",
	MOB_ACTION_MEMORY:       "MEMORY",
	MOB_ACTION_HELPER:       "HELPER",
	MOB_ACTION_NOCHARM:      "NOCHARM",
	MOB_ACTION_NOSUMMON:     "NOSUMMON",
	MOB_ACTION_NOSLEEP:      "NOSLEEP",
	MOB_ACTION_NOBASH:       "NOBASH",
	MOB_ACTION_NOBLIND:      "NOBLIND",
}

// MobActionsToNames converts a mob's action bitvector into a list of bit names
func MobActionsToNames(vector string) ([]string, error) {
	return BitsToNames(vector, MOB_ACTION_NOBLIND, MobActionBits, MobActionChars)
}

const (
	MOB_AFFECTION_BLIND int = 1 << iota
	MOB_AFFECTION_INVISIBLE
	MOB_AFFECTION_DETECT_ALIGN
	MOB_AFFECTION_DETECT_INVIS
	MOB_AFFECTION_DETECT_MAGIC
	MOB_AFFECTION_SENSE_LIFE
	MOB_AFFECTION_WATERWALK
	MOB_AFFECTION_SANCTUARY
	MOB_AFFECTION_GROUP
	MOB_AFFECTION_CURSE
	MOB_AFFECTION_INFRAVISION
	MOB_AFFECTION_POISON
	MOB_AFFECTION_PROTECT_EVIL
	MOB_AFFECTION_PROTECT_GOOD
	MOB_AFFECTION_SLEEP
	MOB_AFFECTION_NOTRACK
	MOB_AFFECTION_UNUSED16
	MOB_AFFECTION_UNUSED17
	MOB_AFFECTION_SNEAK
	MOB_AFFECTION_HIDE
	MOB_AFFECTION_UNUSED20
	MOB_AFFECTION_CHARM
)

var MobAffectionBits = map[int]string{
	MOB_AFFECTION_BLIND:        "BLIND",
	MOB_AFFECTION_INVISIBLE:    "INVISIBLE",
	MOB_AFFECTION_DETECT_ALIGN: "DETECT_ALIGN",
	MOB_AFFECTION_DETECT_INVIS: "DETECT_INVIS",
	MOB_AFFECTION_DETECT_MAGIC: "DETECT_MAGIC",
	MOB_AFFECTION_SENSE_LIFE:   "SENSE_LIFE",
	MOB_AFFECTION_WATERWALK:    "WATERWALK",
	MOB_AFFECTION_SANCTUARY:    "SANCTUARY",
	MOB_AFFECTION_GROUP:        "GROUP",
	MOB_AFFECTION_CURSE:        "CURSE",
	MOB_AFFECTION_INFRAVISION:  "INFRAVISION",
	MOB_AFFECTION_POISON:       "POISON",
	MOB_AFFECTION_PROTECT_EVIL: "PROTECT_EVIL",
	MOB_AFFECTION_PROTECT_GOOD: "PROTECT_GOOD",
	MOB_AFFECTION_SLEEP:        "SLEEP",
	MOB_AFFECTION_NOTRACK:      "NOTRACK",
	MOB_AFFECTION_UNUSED16:     "UNUSED16",
	MOB_AFFECTION_UNUSED17:     "UNUSED17",
	MOB_AFFECTION_SNEAK:        "SNEAK",
	MOB_AFFECTION_HIDE:         "HIDE",
	MOB_AFFECTION_UNUSED20:     "UNUSED20",
	MOB_AFFECTION_CHARM:        "CHARM",
}

var MobAffectionChars = map[rune]string{
	'a': "BLIND",
	'b': "INVISIBLE",
	'c': "DETECT_ALIGN",
	'd': "DETECT_INVIS",
	'e': "DETECT_MAGIC",
	'f': "SENSE_LIFE",
	'g': "WATERWALK",
	'h': "SANCTUARY",
	'i': "GROUP",
	'j': "CURSE",
	'k': "INFRAVISION",
	'l': "POISON",
	'm': "PROTECT_EVIL",
	'n': "PROTECT_GOOD",
	'o': "SLEEP",
	'p': "NOTRACK",
	'q': "UNUSED16",
	'r': "UNUSED17",
	's': "SNEAK",
	't': "HIDE",
	'u': "UNUSED20",
	'v': "CHARM",
}

// MobAffectionsToNames converts a mob's affection bitvector into a list of bit names
func MobAffectionsToNames(vector string) ([]string, error) {
	return BitsToNames(vector, MOB_AFFECTION_CHARM, MobAffectionBits, MobAffectionChars)
}
